config/routes.rb
Portangelescarpenter::Application.routes.draw do
  

  resources :blurbs


  resources :jobs


  resources :skills


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/blurb.rb
class Blurb < ActiveRecord::Base
  attr_accessible :content
end

app/controllers/blurbs_controller.rb
class BlurbsController < ApplicationController
  # GET /blurbs
  # GET /blurbs.json
  def index
    @blurbs = Blurb.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blurbs }
    end
  end

  # GET /blurbs/1
  # GET /blurbs/1.json
  def show
    @blurb = Blurb.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blurb }
    end
  end

  # GET /blurbs/new
  # GET /blurbs/new.json
  def new
    @blurb = Blurb.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blurb }
    end
  end

  # GET /blurbs/1/edit
  def edit
    @blurb = Blurb.find(params[:id])
  end

  # POST /blurbs
  # POST /blurbs.json
  def create
    @blurb = Blurb.new(params[:blurb])

    respond_to do |format|
      if @blurb.save
        format.html { redirect_to @blurb, notice: 'Blurb was successfully created.' }
        format.json { render json: @blurb, status: :created, location: @blurb }
      else
        format.html { render action: "new" }
        format.json { render json: @blurb.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blurbs/1
  # PUT /blurbs/1.json
  def update
    @blurb = Blurb.find(params[:id])

    respond_to do |format|
      if @blurb.update_attributes(params[:blurb])
        format.html { redirect_to @blurb, notice: 'Blurb was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blurb.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blurbs/1
  # DELETE /blurbs/1.json
  def destroy
    @blurb = Blurb.find(params[:id])
    @blurb.destroy

    respond_to do |format|
      format.html { redirect_to blurbs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/blurbs_helper.rb
module BlurbsHelper
end

app/views/blurbs/_form.html.erb
<%= simple_form_for(@blurb) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/blurbs/edit.html.erb
<h1>Editing blurb</h1>

<%= render 'form' %>

<%= link_to 'Show', @blurb %> |
<%= link_to 'Back', blurbs_path %>

app/views/blurbs/index.html.erb
<h1>Listing blurbs</h1>
<hr>
<table class="table">
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blurbs.each do |blurb| %>
  <tr>
    <td><%= blurb.content %></td>
    <td><%= link_to 'Show', blurb %></td>
    <td><%= link_to 'Edit', edit_blurb_path(blurb) %></td>
    <td><%= link_to 'Destroy', blurb, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Blurb', new_blurb_path %>

app/views/blurbs/new.html.erb
<h1>New blurb</h1>

<%= render 'form' %>

<%= link_to 'Back', blurbs_path %>

app/views/blurbs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @blurb.content %>
</p>


<%= link_to 'Edit', edit_blurb_path(@blurb) %> |
<%= link_to 'Back', blurbs_path %>