config/routes.rb
Portangelescarpenter::Application.routes.draw do
  

  resources :blurbs


  resources :jobs


  resources :skills


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :description, :name
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_filter :authenticate_user!
  # GET /skills
  # GET /skills.json
  def index
    authorize! :index, @skill, :message => 'Not authorized as an administrator.'
    @skills = Skill.all
   

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
    end
  end

  # GET /skills/1
  # GET /skills/1.json
  def show
    authorize! :show, @skill, :message => 'Not authorized as an administrator.'
    @skill = Skill.find(params[:id])
   

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    authorize! :new, @skill, :message => 'Not authorized as an administrator.'
    @skill = Skill.new
   

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    authorize! :edit, @skill, :message => 'Not authorized as an administrator.'
    @skill = Skill.find(params[:id])
   
  end

  # POST /skills
  # POST /skills.json
  def create
    authorize! :create, @skill, :message => 'Not authorized as an administrator.'
    @skill = Skill.new(params[:skill])
   

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render json: @skill, status: :created, location: @skill }
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    authorize! :update, @skill, :message => 'Not authorized as an administrator.'
    @skill = Skill.find(params[:id])
   

    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    authorize! :destroy, @skill, :message => 'Not authorized as an administrator.'
    @skill = Skill.find(params[:id])
   
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= simple_form_for(@skill) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h1>Listing skills</h1>
<hr>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skills.each do |skill| %>
  <tr>
    <td><%= skill.name %></td>
    <td><%= skill.description %></td>
    <td><%= link_to 'Show', skill %></td>
    <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
    <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @skill.name %>
</p>

<p>
  <b>Description:</b>
  <%= @skill.description %>
</p>


<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>