config/routes.rb
Portangelescarpenter::Application.routes.draw do
  

  resources :blurbs


  resources :jobs


  resources :skills


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/views/layouts/_footer.html.erb
<div class="log">
	<% if user_signed_in? %>
		<h5><%= link_to "Home", root_path %></h5>
	    <span>
	    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
	    </span>
	    <span>|</span>
	  <% else %>
	    <span>
	    <%= link_to 'Login', new_user_session_path %>
	    </span>
	    <span>|</span>
	  <% end %>
	  <% if user_signed_in? %>
	    <span>
	    <%= link_to 'Edit account', edit_user_registration_path %>
	    </span>
	    <% if current_user.has_role? :admin %>
	      <span>
	      <%= link_to 'Admin', users_path %>
	      </span>
	    <% end %>
	  <% else %>
	    <span>
	    <%= link_to 'Sign up', new_user_registration_path %>
	    </span>
  <% end %>
<div>

<div class="log">
	<% if user_signed_in? %>
	    <span>
	    <%= link_to 'Skills', skills_path %>
	    </span>
	    <span>|</span>
	    <span>
	    <%= link_to 'Jobs', jobs_path %>
	     </span>
	     <span>|</span>
	    <span>
	    <%= link_to 'Summary', blurbs_path %>
	    </span>
  <% end %>
<div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="span9">
  <%= image_tag('peter_holland.png', :class => "img-polaroid")  %>


  <h1>Peter Holland</h1>
  <h6>Carpenter and Handyman</h6>
  <p>"Experienced commercial and home carpentry. I build from foundation to finish."</p>

  <div class="clearfix"></div>
  </div>
  <div class="span3 hidden-phone">
  <ul>
    <li><i class="icon-envelope-alt"></i> peter1457@outlook.com</li>
    <li><i class="icon-home"></i> Port Angeles, WA</li>
    <li><i class="icon-user"></i> (360) 461-4449</li>
    <li><%= link_to "Print Resume", "#", :class => "btn btn-success", onclick: "printpage()" %></li>
    <!--li><%#= link_to "Download Resume PDF", "#", :class => "btn btn-warning btn-mini" #%></li-->
  </ul>



  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Peter Holland | Port Angeles Carpenter" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Peter Holland is a carpenter located in Port Angeles, WA" %>">
    <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Milonga|Roboto+Slab"%>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= stylesheet_link_tag "print", :media => "print" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="header">
      <div class="container" style="width: 980px">
        <div class="row-fluid">
          <%= render 'layouts/navigation' %>
        </div>
      </div>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          <%= render 'layouts/footer' %>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>